### ISSUE TITLE
Artist "Yes" triggers alerts for other artists

### ISSUE THREAD

**Issue by owenhu99** [jsookikian/vinyldealbot#1]
The artist name "Yes" triggers alerts for other artists with the name "yes" in them, for example "Trophy Eyes" and "The Eyes of Stanley Pain".

**Comment by jsookikian** [comment]
I've played around with a few different solutions to this. Right now, I am searching the post title string for the artist name with a space after the artist. I tried introducing a space before, but it would end up excluding any post that started with the artist names. 

[Link to code](https://github.com/jsookikian/vinyldealbot/blob/2f84f8f43e956f2a2f2d25f7ee6ee298c41cf03b/bot.py#L161)
```
def titleContainsArtist(artist, title)
    cases = [artist + " ", artist + ";", artist + ":", artist + ";", artist + ","]
    for case in cases:
        if title.find(case) > 0:
            return True
    return False
```

If you have any ideas, feel free to jot them down.

**Comment by owenhu99** [comment]
@jsookikian I created a pull request for an alternative function design, take a look :)

**Comment by jsookikian** [comment]
I'll push the code down to the server when I get home and have access to my machine. Thanks for the contribution!

**Comment by owenhu99** [comment]
@jsookikian great! no problem. that was my first github contribution, so it took me a while to understand the process :)

**Comment by jsookikian** [comment]
haha yeah it does take a bit, but you get used to it. I've actually been meaning to fix this issue for a long time because when I initially wrote it, I didn't really think about all of the edge cases. So, when I started running it, I was like meh it works haha
